apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData: # dojdzie do szyfrowania
  username: "admin"
  password: "adminpassword"
  mongodb-uri: "mongodb://admin:adminpassword@mongodb-service:27017/sportsfacility?authSource=admin"